version: "3"
services:
  dbpolicia:
    build: .
    container_name: "pjc"
    env_file:
      - config.env
    volumes:
      - pg-data:/pg/data/
      - pg-backup:/pg/backup/
      - pg-log:/pg/log/
      - pg-wal:/pg/wal/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      policia:
        ipv4_address: "192.168.0.1"

volumes:
  pg-data:
  pg-backup:
  pg-log:
  pg-wal:

networks:
  policia:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/27"
          ip_range: "192.168.0.0/27"
          gateway: "192.168.0.30"
          dns:
            - 8.8.8.8
            - 8.8.4.4
